AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECR repository for Strands Agent'

Parameters:
  ProjectName:
    Type: String
    Default: agentic-sales-analyst

Resources:
  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref ProjectName
      ImageScanningConfiguration:
        ScanOnPush: true
      EncryptionConfiguration:
        EncryptionType: KMS
      ImageTagMutability: IMMUTABLE
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [{
              "rulePriority": 1,
              "description": "Keep last 10 images",
              "selection": {
                "tagStatus": "any",
                "countType": "imageCountMoreThan",
                "countNumber": 10
              },
              "action": {"type": "expire"}
            }]
          }

Outputs:
  RepositoryUri:
    Value: !GetAtt Repository.RepositoryUri
    Export:
      Name: !Sub ${ProjectName}-ecr-uri
